server:
  port: 8012
dubbo:
  application:
    name: dubbo-provider
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20880
spring:
  cache:
    ehcache:
      config: ehcache.xml

redis